/********************************************************************
* eventdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventdict();
extern void G__cpp_setup_inheritanceeventdict();
extern void G__cpp_setup_typetableeventdict();
extern void G__cpp_setup_memvareventdict();
extern void G__cpp_setup_globaleventdict();
extern void G__cpp_setup_memfunceventdict();
extern void G__cpp_setup_funceventdict();
extern void G__set_cpp_environmenteventdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./MyEvtId.h"
#include "./MyPart.h"
#include "./MyGenPart.h"
#include "./MyVertex.h"
#include "./MySimVertex.h"
#include "./MyBeamSpot.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventdictLN_TClass;
extern G__linked_taginfo G__eventdictLN_TBuffer;
extern G__linked_taginfo G__eventdictLN_TMemberInspector;
extern G__linked_taginfo G__eventdictLN_TObject;
extern G__linked_taginfo G__eventdictLN_string;
extern G__linked_taginfo G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_MyEvtId;
extern G__linked_taginfo G__eventdictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__eventdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__eventdictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__eventdictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__eventdictLN_TLorentzVector;
extern G__linked_taginfo G__eventdictLN_MyPart;
extern G__linked_taginfo G__eventdictLN_MyGenPart;
extern G__linked_taginfo G__eventdictLN_MyVertex;
extern G__linked_taginfo G__eventdictLN_MySimVertex;
extern G__linked_taginfo G__eventdictLN_MyBeamSpot;
extern G__linked_taginfo G__eventdictLN_vectorlEMyGenPartcOallocatorlEMyGenPartgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEMyGenPartcOallocatorlEMyGenPartgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEMyGenPartcOallocatorlEMyGenPartgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictLN_vectorlEMyVertexcOallocatorlEMyVertexgRsPgR;
extern G__linked_taginfo G__eventdictLN_vectorlEMyVertexcOallocatorlEMyVertexgRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEMyVertexcOallocatorlEMyVertexgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<MyGenPart,allocator<MyGenPart> > G__vectorlEMyGenPartcOallocatorlEMyGenPartgRsPgR;
typedef vector<MyVertex,allocator<MyVertex> > G__vectorlEMyVertexcOallocatorlEMyVertexgRsPgR;
